version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: plants_postgres
    environment:
      POSTGRES_USER: plant_user
      POSTGRES_PASSWORD: plant_password
      POSTGRES_DB: plant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plants_network

volumes:
  postgres_data:

networks:
  plants_network:
